version: '3.8'

services:
  my_python_dev_container:
    image: py_test #python:3.10
    container_name: py_3_10_12
    ports:
      - "8701:8501"
    working_dir: /app
    #command: python3 app.py
    command: tail -f /dev/null #keep it running

#docker exec -it py_3_10_12 /bin/bash
#podman exec -it py_3_10_12 /bin/bash