version: '3'

services:
  streamlit-multichat:
    image: ghcr.io/jalcocert/streamlit-multichat:v1.0 #streamllama
    container_name: streamlit_multichat
    volumes:
      - ai_streamlit_multichat:/app
    working_dir: /app  # Set the working directory to /app
    command: /bin/sh -c "streamlit run Z_multichat.py"    
    #command: streamlit run appv2.py # tail -f /dev/null
    ports:
      - "8501:8501"    

volumes:
  ai_streamlit_multichat:

#docker run -p 8501:8501 -v ai_streamlit_multichat:/app --name streamlit_ollama streamllama:latest /bin/sh -c "cd /app && streamlit run streamlit-multichat.py"
#podman run -p .....

#docker-compose up -d